# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3665464d1a53fcc72afb1bf24f4acf8d060e3befc1302fb3f8a65b44efa8ce60992089024aa35fb964e7ae411547504a8d247f0e2eef5021ce56d1df37ac231

test:
  secret_key_base: a4053519fc0cc9fbe2e6e0f011318e739176c8777fd7faf0077f0bc969c42d6b4821efd6f3cb4126c23179ba6298a0cde22e1310bbd4639d3578bcbe549ff164

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
